steps:
# Uses the ubuntu build step:
# to run a shell script and set TAG
- name: 'ubuntu'
  args: ['bash', './.scripts/set_tag.sh']
  id: 'set_tag'

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag=gcr.io/$PROJECT_ID/cloud-builders-helm:latest'
  - '--tag=gcr.io/$PROJECT_ID/cloud-builders-helm:$BRANCH_NAME'
  - '.'
  id: 'build_image'

images:
- 'gcr.io/$PROJECT_ID/cloud-builders-helm:latest'
- 'gcr.io/$PROJECT_ID/cloud-builders-helm:$BRANCH_NAME'
